# Generated by Django 4.1.1 on 2022-09-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.CharField(choices=[('frontend', 'FRONTEND'), ('backend', 'BACKEND'), ('fullstack', 'FULLSTACK'), ('uxdesigner', 'UXDESIGNER')], default='fullstack', max_length=20),
        ),
    ]
