# Generated by Django 4.1.1 on 2022-10-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
