# Generated by Django 4.1.1 on 2022-10-03 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_name_profile_f_name_profile_l_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
