# Generated by Django 4.1.1 on 2022-10-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_f_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
