# Generated by Django 4.1.1 on 2022-09-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_feautured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feautured_image',
            new_name='featured_image',
        ),
    ]
