# Generated by Django 4.1.1 on 2022-10-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectmembers_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='project',
            new_name='project_review',
        ),
        migrations.RemoveField(
            model_name='projectmembers',
            name='project_id',
        ),
    ]
